version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: extractor_redis

  worker:
    build: .
    container_name: extractor_worker
    command: celery -A app.worker.celery worker --loglevel=info
    volumes:
      - ./downloads:/app/downloads  # Volume compartilhado
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  web:
    build: .
    container_name: extractor_web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app              # Hot-reload do c√≥digo
      - ./downloads:/app/downloads  # Volume compartilhado
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
