services:
  app:
    build: .
    container_name: sonicstream
    restart: always
    ports:
      - "8090:8000"
    volumes:
      - ./downloads:/app/downloads

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: sonicstream_tunnel
    restart: always
    # Comando para criar tunel rápido para o serviço 'app' na porta 8000
    command: tunnel --url http://app:8000
